create or replace TRIGGER NEW_RESERVATION
AFTER INSERT ON PASSANGER_LIST
FOR EACH ROW
BEGIN
  update FLIGHT
  set RESERVED_SEAT_NO = RESERVED_SEAT_NO + 1
  where FLIGHT.ID = :new.FLIGHT_ID;
END;
/


create or replace TRIGGER PILOT_PASSPORT_UPDATE
BEFORE update  of PASSPORT_NUMBER on PERSON
FOR EACH ROW
BEGIN
  update PILOT
  set PASSPORT_NUMBER = :new.PASSPORT_NUMBER
  where PILOT.PASSPORT_NUMBER = :old.PASSPORT_NUMBER;
END;
/

create or replace TRIGGER PASSANGER_PASSPORT_UPDATE
BEFORE update  of PASSPORT_NUMBER on PERSON
FOR EACH ROW
BEGIN
  update PASSANGER
  set PASSPORT_NUMBER = :new.PASSPORT_NUMBER
  where PASSANGER.PASSPORT_NUMBER = :old.PASSPORT_NUMBER;
END;
/

create or replace TRIGGER CONTR_PASSPORT_UPDATE
AFTER update of PASSPORT_NUMBER on PERSON
FOR EACH ROW
BEGIN
  update TRAFFIC_CONTROLLER
  set PASSPORT_NUMBER = :new.PASSPORT_NUMBER
  where TRAFFIC_CONTROLLER.PASSPORT_NUMBER = :old.PASSPORT_NUMBER;
END;
/

create or replace TRIGGER FLIGHT_DELETE
BEFORE DELETE on FLIGHT
FOR EACH ROW
BEGIN
  DELETE PASSANGER_LIST
  where PASSANGER_LIST.FLIGHT_ID = :old.ID;
END;
/